name: Build SFA

on:
  workflow_dispatch:
  # push:
    # branches:
      # - dev-next
      # - main-next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'
          check-latest: true

      - name: checkout app repository
        uses: actions/checkout@v5
        with:
          ref: dev
          path: sfa
          repository: SagerNet/sing-box-for-android
          submodules: recursive

      - name: setup ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r28

      - name: Setup OpenJDK
        run: |-
          sudo apt update && sudo apt install -y openjdk-17-jdk-headless
          /usr/lib/jvm/java-17-openjdk-amd64/bin/java --version

      - name: get latest build tools version
        id: sdk
        run: echo version=$(ls $ANDROID_HOME/build-tools | tail -n 1) >> $GITHUB_OUTPUT

      - name: get sing-box version
        id: sing-box
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box
          git fetch --tags --force sekai
          if [ "${{ github.ref_name }}" == "dev-next" ]; then
            TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          else
            TAG=$(git describe --tags --abbrev=0)
          fi
          REV=$(git rev-parse --short HEAD)
          echo "version=${TAG}-${REV}" >> $GITHUB_OUTPUT

      - name: build libbox
        env:
          CC: ${{steps.setup-ndk.outputs.ndk-path}}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          TAGS: with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_utls,with_clash_api,with_gvisor,with_proxyproviders,with_fallback,with_loadbalance
          VERSION: ${{steps.sing-box.outputs.version}}
          CGO_ENABLED: '0'
        run: |
          make lib_install
          export PATH="$PATH:$(go env GOPATH)/bin"
          make lib_android

      - name: setup build env && build app
        env:
          VERSION: ${{steps.sing-box.outputs.version}}
          KEYSTORE: ${{secrets.SIGN_KEY}}
          ALIAS_NAME: ${{secrets.ALIAS}}
          KEYSTORE_PASS: ${{secrets.SIGN_KEY}}
        run: |
          mkdir -p sfa/app/libs/
          cp ./libbox.aar sfa/app/libs/
          cd sfa
          echo "" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC" >> gradle.properties
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.parallel=true" >> gradle.properties
          echo "VERSION_NAME=${VERSION}" > local.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> local.properties
          if [ -f app/build.gradle ]; then
            sed -i '/signingConfigs\.release/d' app/build.gradle
          fi
          if [ -f app/build.gradle.kts ]; then
            sed -i '/signingConfigs\.release/d' app/build.gradle.kts
          fi
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: sign app
        uses: PuerNya/sign-android-release@v2.0.4
        env:
          BUILD_TOOLS_VERSION: ${{steps.sdk.outputs.version}}
        with:
          alias: ${{secrets.ALIAS}}
          releaseDirectory: sfa/app/build/outputs/apk/other/release
          signingKeyBase64: ${{secrets.SIGN_KEY}}
          keyStorePassword: ${{secrets.KEY_STORE_PASSWORD}}

      - name: upload arm64-v8a apk
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: sfa-${{env.version}}-arm64-v8a
          path: sfa/app/build/outputs/apk/other/release/*-arm64-v8a-signed.apk
          compression-level: 9

      - name: upload armeabi-v7a apk
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: sfa-${{env.version}}-armeabi-v7a
          path: sfa/app/build/outputs/apk/other/release/*-armeabi-v7a-signed.apk
          compression-level: 9

      - name: upload x86_64 apk
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: sfa-${{env.version}}-x86_64
          path: sfa/app/build/outputs/apk/other/release/*-x86_64-signed.apk
          compression-level: 9

      - name: upload x86 apk
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: sfa-${{env.version}}-x86
          path: sfa/app/build/outputs/apk/other/release/*-x86-signed.apk
          compression-level: 9

      - name: upload universal apk
        uses: actions/upload-artifact@v4.1.0
        env:
          version: ${{steps.sing-box.outputs.version}}
        with:
          name: sfa-${{env.version}}-universal
          path: sfa/app/build/outputs/apk/other/release/*-universal-signed.apk
          compression-level: 9

  Upload-Release:
    permissions: write-all
    if: ${{ github.ref_type == 'branch' && !startsWith(github.event_name, 'pull_request') }}
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get Version
        run: |
          git remote add upstream https://github.com/SagerNet/sing-box.git
          git fetch --tags --force upstream
          if [ "${{ github.ref_name }}" == "dev-next" ]; then
            echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
          else
            echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          fi
        shell: bash

      - uses: actions/download-artifact@v4
        with:
          path: sfa/app/build/outputs/apk/other/release/
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: sfa/app/build/outputs/apk/other/release

      - name: Set Env
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
        shell: bash

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: |
          cat > release.txt << 'EOF'
          Release created at  ${{ env.BUILDTIME }}
          EOF

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{  success() && github.ref_name == 'dev-next' }}
        with:
          tag_name: ${{ env.TAG }}
          files: |
            sfa/app/build/outputs/apk/other/release/*
          prerelease: true
          generate_release_notes: true
          body_path: release.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{  success() && github.ref_name != 'dev-next' }}
        with:
          tag_name: ${{ env.TAG }}
          files: |
            sfa/app/build/outputs/apk/other/release/*
          prerelease: false
          generate_release_notes: true
          body_path: release.txt
